# Generated by Django 4.1 on 2022-09-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='Class',
            new_name='class',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Class',
            new_name='class',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Sex',
            new_name='sex',
        ),
    ]
